name: Lucid Insights
favicon: null
layout_spectrum: 0.7582979600410908
typography_spectrum: 0.06781387934461236
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8239803537726402
  lightness: 0.2808634957764298
  saturation: 0.011179063003510237
  rhythmicContrast: 0.462166071170941
purpose: []
